### ISSUE TITLE
Build a conda-forge feedstock

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_to_cmip#3]
This looks like an easy recipe to move over to conda-forge.  I'll work on a feedstock in the next couple of days.

**Comment by xylar** [comment]
@sterlingbaldwin, for a conda recipe to be accepted, we'll need:
* a license file
* a tag or a release we can point to

Could you take care of these two as soon as you can so I can do the rest?

**Comment by sterlingbaldwin** [comment]
Will do.

**Comment by xylar** [comment]
It looks like at least a few alterations to the package will be needed before this is ready to go to conda-forge.  I'll make a pull request in the next day or 2 with some mods.

**Comment by xylar** [comment]
@sterlingbaldwin, I just tested the recipe for conda-forge below and every worked as expected.  When you're ready, please make a new release.  At that point, I'll point the recipe to that release and get this up on conda-forge.

```
{% set name = "e3sm_to_cmip" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #url: https://github.com/E3SM-Project/{{ name }}/archive/v{{ version }}.tar.gz
  #sha256: d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f
  git_url: git://github.com/E3SM-Project/e3sm_to_cmip.git
  git_tag: master

build:
  skip: True  # [win or py<36]
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - nco
    - cmor >=3.5.0
    - cdutil
    - cdms2 >=3.1
    - progressbar2
    - pathos
    - pyyaml
    - xarray
    - netcdf4
    - dask
    - scipy

test:
  commands:
    - e3sm_to_cmip --help
  imports:
    - e3sm_to_cmip

about:
  home: https://github.com/E3SM-Project/e3sm_to_cmip
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A cli utility to transform E3SM model output into CMIP compatible data.'
  description: |
    Transform e3sm time series variables into cmip compatible data. Each
    variable needs its own handler script, implemented in the cmor_handlers
    directory (see directory for current handlers). In addition, you will need
    to clone the cmor repo (https://github.com/PCMDI/cmor) to access the Test
    and Tables directories. Test holds the common_user_input.json file which
    can be used as a placeholder for the user supplied metadata, and Tables
    holds all the CMIP6 variable tables.
  doc_url: https://github.com/E3SM-Project/e3sm_to_cmip
  dev_url: https://github.com/E3SM-Project/e3sm_to_cmip

extra:
  recipe-maintainers:
    - xylar
    - sterlingbaldwin
```
